language: php

php:
  - 5.3
  - 5.4
  - 5.5
  
matrix:
  allow_failures:
    - php: 5.5

before_script: composer install --dev --no-interaction --prefer-source

branches:
  only:
    - master

notifications:
  email:
    - kotlyar.maksim@gmail.com