language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.1.*
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source --no-update
  - composer install --dev --prefer-source

notifications:
  email:
    - payumsupport@forma-pro.com
